name: Verify Version Compatibility

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/patrol_cli/lib/src/compatibility_checker/version_compatibility.dart'
      - 'packages/patrol_cli/test/src/compatibility_checker/version_compatibility_test.dart'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/patrol_cli/lib/src/compatibility_checker/version_compatibility.dart'
      - 'packages/patrol_cli/test/src/compatibility_checker/version_compatibility_test.dart'

jobs:
  verify:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Dart
      uses: dart-lang/setup-dart@v1
    
    - name: Install dependencies
      run: |
        cd packages/patrol_cli
        dart pub get
    
    - name: Run compatibility tests
      run: |
        cd packages/patrol_cli
        dart test test/src/compatibility_checker/version_compatibility_test.dart
    
    - name: Generate compatibility table
      run: |
        cd packages/patrol_cli
        dart run lib/src/compatibility_checker/generate_compatibility_table.dart
    
    - name: Verify table is up to date
      run: |
        if [[ -n $(git status --porcelain docs/documentation/compatibility-table.mdx) ]]; then
          echo "Compatibility table is not up to date. Please run 'dart run lib/src/compatibility_checker/generate_compatibility_table.dart' and commit the changes."
          exit 1
        fi 